/* ======================================================
   INSIGHT TYPES — SINGLE SOURCE OF TRUTH (PRODUCTION)

   ✔ Engine-safe
   ✔ Explainable
   ✔ Auditable
   ✔ UI + DB compatible
====================================================== */

import type { InsightId } from "@/lib/insights/ids"

/* ===============================
   Insight Severity
=============================== */

export type InsightKind = "warning" | "info" | "success"

/* ===============================
   Dashboard Metrics
=============================== */
/**
 * Computed once per request
 * Passed into insight engine
 */
export type DashboardMetrics = {
  todayRevenue: number
  totalRevenue: number
  bestSellingProduct: string | null
  failedPayments7d: number
  refundedAmount7d: number
}

/* ===============================
   Insight Meta (Explainability)
=============================== */
/**
 * Used by:
 * - Explainability Engine
 * - Audit Logger
 * - Debug Panel
 */
export type InsightMeta = {
  ruleName: string           // e.g. "FAILED_PAYMENTS_7D"
  metricKey: keyof DashboardMetrics | string
}

/* ===============================
   Core Insight Object
=============================== */
/**
 * Insight generated by the engine
 * Pure data — no UI / DB concerns
 */
export type Insight = {
  /**
   * 🔒 LOCKED insight identifier
   * Must come from INSIGHT_IDS registry
   */
  id: InsightId

  kind: InsightKind
  title: string
  body: string

  /**
   * Lower = higher priority
   * (sorted ascending)
   */
  priority: number

  /**
   * 🔥 Mandatory for explainability
   */
  meta: InsightMeta
}

/* ===============================
   Insight Rule Signature
=============================== */
/**
 * Pure function:
 * metrics → Insight | null
 */
export type InsightRule = (
  metrics: DashboardMetrics
) => Insight | null

/* ===============================
   Optional — Engine Output
=============================== */
/**
 * Used by evaluate.ts
 */
export type EvaluatedInsight = Insight & {
  decisionReason:
    | "first_time"
    | "cooldown_active"
    | "cooldown_expired"
    | "severity_escalated"
    | "dismissed_no_change"
}